name: Cypress Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm ci
    - name: Run cypress tests
      run: npm run test
      if: always()

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Generate Allure report with history
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history